### ISSUE TITLE
Undefined offset error

### ISSUE THREAD

**Issue by rumblestrut** [davidstanley01/MovieCommit#11]
I keep getting an undefined offset error as it loops through the data. I don't see a pattern; it's just random.

So, to clarify, it loops through and usually displays the quote, but every so often will show this:

Details

Type: ErrorException
Code: 8
Message: Undefined offset: 28
File: /Users/egruber/Sites/Sandbox/MovieCommit/src/MovieCommit/MovieCommit.php
Line: 169

**Comment by davidstanley01** [comment]
Fixed it. Wasn't properly accounting for both the title at the first line and the 0 index of the array.
